### ISSUE TITLE
How to re-throw exceptions? 

### ISSUE THREAD

**Issue by jinshiyi11** [BoltsFramework/Bolts-Android#110]
Right now Bolts makes it hard to debug unhandled exceptions since they're suppressed at the moment

**Comment by grantland** [comment]
Could you please elaborate on your issue?

Exceptions thrown inside a continuation or returned by a continuation can be handled in the following continuation via `task.isFaulted()` and `task.getError()`.

**Comment by jinshiyi11** [comment]
When there is fatal error in my task,Bolts catchs the exception,and i can not throw the exception out.

```java
Task.call(new Callable<Void>(){

            @Override
            public Void call() throws Exception {
                //fatal error occurred,Bolts catch this exception
                throw new NullPointerException();
                //return null;
            }
        }).continueWith(new Continuation<Void, Void>() {

            @Override
            public Void then(Task<Void> task) throws Exception {

                if(task.isFaulted()){
                    //fatal error occurred and i want my app can crash so rethrow the exception,but Bolts catch the exception again
                    throw task.getError();
                }

                return null;
            }
        },Task.BACKGROUND_EXECUTOR);
```

**Comment by grantland** [comment]
`Exception`s are defined by being recoverable exceptions and `Error`s would be used for unrecoverable exceptions. `Task` does not catch `Error`s so this would cause your application to crash like you wanted. Could you elaborate a little more on what's throwing an `Exception` and why you want it to crash the app?

There's a new feature that was just contributed (#106) that would allow you to handle unhandled `Exception`s, though the reasoning behind this feature is a bit different as it's aimed to prevent bad code and removed in production.

Otherwise, if you _really_ want to crash your application due to an `Exception` thrown in a `Task`, you'd have to pass the `Exception` to your application's main thread due to `Task`'s asynchronous nature.

A simple example that would block the main thread:

```java
Task<Void> task = doAsync();

task.waitForCompletion();
if (task.isFaulted()) {
  throw new MyWrapperException(task.getError()); // wrapping not required, but nice to have a complete stack trace
}
```
