### ISSUE TITLE
Easier way to unit test background Tasks

### ISSUE THREAD

**Issue by guillaume-tgl** [BoltsFramework/Bolts-Android#141]
This is a suggestion:
It'd be great to be able, in unit tests, to run all the tasks on the UI thread, even the ones that were set up to run on a background thread. This would make testing code with Tasks easier.

Right now, the solution to unit test some code where a background Task is to set up a custom background executor and change it during tests. See https://medium.com/@trionkidnapper/unit-testing-asynchronous-tasks-from-bolts-android-e780f02bf1be#88c7

**Comment by grantland** [comment]
I'd actually recommend explicitly passing in a background executor for this reason. Detecting being run in a unit test is pretty risky and being able to swap out the passed through executor at test time via injection is more useful as you can specify either run immediately or even an executor you can step through.

Great post otherwise!
