### ISSUE TITLE
Question: how to handle activity rotation / re-creation lifecycle with Tasks?

### ISSUE THREAD

**Issue by danielesegato** [BoltsFramework/Bolts-Android#37]
Hi,

This is not a bug, nor a feature request. This is a question.

Bolts seems a very nice library, but I do not really understand how you pictured its usage along with the Android lifecycle.

Suppose I do obtain a Task:

    Task<MyResult> myTask = ....;

Now I want to somehow link that task to my UI (show a spinner before showing the result or things like this).

I have to maintain that task across activity recreation.

* Placing it in static variable is bad practice.
* I can create a Loader, but then why do I need a task? My loader will just wait for the result and give me it
* I can associate my task to the ApplicationContext (instead of the activity) and modify the database or a shared preference and update the UI: it's a lot more work then with a loader that does the thing

I'm sure you considered this while developing bolts, how am I supposed to retain the Task, or at least a callback to it across activity instances (destroy/recreate cycle)?

Thanks

**Comment by JosephEarl** [comment]
I would not say this issue is anything in particular to do with the concept of Tasks or their implementation.

# Option 1
Run the task in a retained fragment. This is the general guidance from the Android team for operations that are closely connected to the UI (i.e. that only run where there is a UI). See http://developer.android.com/guide/topics/resources/runtime-changes.html#RetainingAnObject
The fragment will then need to call back to the Activity.

# Option 2
Don't run Tasks or asynchronous methods in your Activity context. Run them in your Application context or Service context and use an Event Bus to send events to your UI components.

**Comment by grantland** [comment]
^ this is the recommended way to do things. Tasks aren't meant to be a replacement for Loaders/AsyncTask/etc, but a useful tool to compose multiple asynchronous operations. How you notify your UI of changes after the asynchronous work is done in the context of an Activity is currently outside the realm of Tasks.

I'll be closing this issue since it seems to be resolved, but feel free to open a new issue if you'd like to continue this discussion.
